# \gcp-endpoints\openapi.yaml
swagger: "2.0"
info:
  title: "Google AI"
  description: "Transcreever audio"
  version: "1.0.0"
# This field will be replaced by the deploy_api.sh script.
host: "bright-sunlight-423018-i7.appspot.com"
schemes:
  - "https"